### ISSUE TITLE
Don't accept the same QR code multiple times when 'combining'

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/banana_split#15]
Suggestion: either ignore when same qr code is presented again or show error message

**Comment by prybalko** [comment]
@emostov just curious, are you still working on this issue?

**Comment by emostov** [comment]
@prybalko - no. @dvdplm might be able to shed more light on the current plans for this project

**Comment by prybalko** [comment]
I'm going to close this ticket because I'm not able to reproduce it. Feel free to reopen it if that's still an issue
