### ISSUE TITLE
Improve the texts

### ISSUE THREAD

**Issue by kirushik** [paritytech/banana_split#37]
Especially on the "landing" page -- it currently does a pretty poor job at explaining what the hell is going on.

**Comment by kirushik** [comment]
Document with suggested wording improvements: https://docs.google.com/document/d/1eQ6VaKVs3Sn9we2fs2NRAljALsJd6BH12rGGhwAUAX0/edit?usp=sharing

**Comment by prybalko** [comment]
Fixed in https://github.com/paritytech/banana_split/pull/78
