### ISSUE TITLE
Support camera-less devices 

### ISSUE THREAD

**Issue by prybalko** [paritytech/banana_split#72]
As a user with a desktop computer
When I restore my secret
I'd like to insert QR code content as text
Because I don't have a camera on my PC but have one on my phone. 

Also, this feature will ease the process of gathering secrets from multiple people.

**Comment by kirushik** [comment]
This is a feature, not a but.
Contents of QR codes _shouldn't be_ recoverable remotely, only in-person (to avoid impersonation attacks via hacked accounts, for example).
So shards not existing outside of physical papers with QR codes is desireable.

You _can_ use the webapp from your phone, though. (At least on Android, never tested BS in Mobile Safari.)


PS. Damn, I've really shouldn't have saved time on outlining the threat and security models here...
