### ISSUE TITLE
Recovery passphrase truncated (canva's size)

### ISSUE THREAD

**Issue by chevdor** [paritytech/banana_split#76]
![image](https://user-images.githubusercontent.com/738724/141943950-689a406b-dcb2-47d8-a24e-7edee68107ad.png)

**Comment by prybalko** [comment]
Please provide more information, I'm not able to reproduce it.
What version of `banana split` are you using? Is it the one deployed on `https://bs.parity.io` or from `master` branch?
What device and browser are you using?

**Comment by chevdor** [comment]
I am using https://bs.parity.io and Brave.
I did download the html and opened it. I did not go offline but cheated for the test using:
![image](https://user-images.githubusercontent.com/738724/141946374-c9411bc0-36e3-47cb-9317-954c7b93c575.png)

The issues seems to be the width only. Could you share for reference a screenshot of how it looks like when it works ?

**Comment by prybalko** [comment]
Here is how it looks to me.
Chromium 95.0.4638.69 (Official Build) Arch Linux (64-bit)

![image](https://user-images.githubusercontent.com/7165377/141948617-e6e53ce2-4df4-4dc5-9cc4-d287c670a0e8.png)

**Comment by chevdor** [comment]
ok, so I miss a big chunk.
The canvas on my end is a fixed 30 pixels width which sounds definitely wrong.

**Comment by kirushik** [comment]
@chevdor Brave returns zero from [`context.measureText` call](https://github.com/paritytech/banana_split/blob/master/src/components/CanvasText.vue#L22) which is used to determine the appropriate canvas width in our component.
It is a well-known behavior intended to protect against browser fingerprinting, as documented in https://github.com/brave/brave-browser/issues/1738

@prybalko probably we can detect `measureText` returning zero here, and fallback to some more sensible default than just 20px? I think privacy-conscious users would prefer the text being placed off-center in an ugly way over it not being visible at all.

**Comment by kirushik** [comment]
@chevdor maybe you can test if Brave supports measuring text via DOM (like it is done [here](https://github.com/hustcc/bmt/blob/master/src/dom.ts)), so we can use it as a fallback for measuring it using the canvas API?
