### ISSUE TITLE
QR upload is needed for desktop-only flow

### ISSUE THREAD

**Issue by dandaka** [paritytech/banana_split#83]
Now

1. User on desktop creates QR codes with app
2. Wants to restore
3. The only option is to scan QR with webcam

This flow expects either of those
a/ A second device with secrets on it (smartphone)
b/ A printer and printing action

Expected

UI allows uploading PNG files created by app

**Comment by dandaka** [comment]
I see a related issue #72

**Comment by kirushik** [comment]
No, sorry, this is not a feature which makes sense in context of BananaSplit.
The idea is to only allow users to have their QR codes as _physical artifacts_; under no circumstances should we encourage people to make a _digital image_ of their QR code — it's notoriously hard to erase file without trace on any modern computing hardware, so it will inevitably lead to some users being compromised via hackers obtaining such QR codes copies and recovering the secrets.

It's pretty possible to _split_ shards on a device without camera — but recovering on one should just not possible, and that's end of story.

I understand your struggle in context of #84 — now __that's__ a legitimate bug we might at least try to address.

But this one is, unfortunately, won't fix.
If it's absolutely necessary to work with digital shares, some semi-synchronous multiparty protocol like https://darkcrystal.pw/ might be a better option.
